name: CampfireEffects
version: 1.0.0
author: OtherOne
main: me.otherone.campfire.CampfireEffects
api-version: 1.16

commands:
  campfireeffects:

permissions:
  campfireeffects.reload:
    description: Gives reload permission.